DELETE http://localhost:4001/api/tickets/3d845b70-42f0-4305-9780-66c1945b7a3b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjkxNTJkMDE3YWZjOWE3YmY4ZjQ1YmYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjEwMzY3NzEsImV4cCI6MTcyMTA0MDM3MX0.RvrY8a2G_W0Mf_HTT5_VlzEKyAZYVE85Ww2h8HMM5PA